def bubble_sort(arr):   #O(1)
    n=len(arr)  #O(1)
    for i in range(n): #O(n)
        swap=False #O(1)
        for d in range(0,n-i-1): #O(n)
            if arr[d]>arr[d+1]: #O(1)
                arr[d],arr[d+1]=arr[d+1],arr[d] #O(1)
                swap=True #O(1)
        if not swap: #O(1)
            break #O(1)
    return arr  #O(1)

numbers=[5,3,8,4]  #O(1)
print(bubble_sort(numbers))  #O(n^2)